user_input = input("Enter numbers separated by space: ")
numlist = list(map(int, user_input.split()))
total = sum(numlist)
maximum = max(numlist)
minimum = min(numlist)
print("List:", numlist)
print("Sum:", total)
print("Maximum:", maximum)
print("Minimum:", minimum)
